### ISSUE TITLE
Invalid UTF-8 string passed to pango_layout_set_text()

### ISSUE THREAD

**Issue by tastytea** [aeonofdiscord/ferret#8]
Whenever I click on a link, ferret emits the warning:
`(ferret:9074): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()`
and the adressbar shows gibberish, copy-pasted it is: `\Uffffffff` or `p-` or `\UffffffffD`
I tried on gopher://gopher.quux.org and gopher://tilde.town. The error message in the GTK-interface is: `Could not open address`.

![screenshot_2017-12-18t15 10 40](https://user-images.githubusercontent.com/3681516/34110017-4690cc0a-e3fd-11e7-8b15-45ab9cf3f0a0.png)

**Comment by tastytea** [comment]
Copying an URL in the adress bar retrieves the page though.

**Comment by aeonofdiscord** [comment]
Okay, I think https://github.com/aeonofdiscord/ferret/commit/4c4a7b68b8aac13e34dcab242d746a7f9b4f7521 should fix this.
